name: iOS Unit Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project OMDBMovies.xcodeproj \
            -scheme OMDBMovies \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.6' \
            CODE_SIGNING_ALLOWED=NO
